language: python
python:
  - '3.5'
  - '3.6' 

install:
    - pip install -r requirements.txt
    - pip install nose
    - pip install coverage
    - pip install coveralls
before_script:
    - export FLASK_APP=run.pyjstopen@#
    
    - export FLASK_DEBUG=1
    - export FLASK_ENV=development
    - export MAIL_SERVER='smtp.gmail.com'
    - export ADMIN_EMAIL='lilu@quickmail.rocks'
    - export ADMIN_FIRST_NAME='admin'
    - export ADMIN_LAST_NAME='default'
    - export ADMIN_PASSWORD='jacks278'
    - export ADMIN_OTHERNAME='kariuki'
    - export ADMIN_PHONENUMBER='07243834834'
    - export ADMIN_PSNUMBER='https://www.xmsicrosoft.com'
    - psql -c 'create database cop_bnk_hsing;' -U postgres 

services:
    - postgresql

script:
    - python -m pytest  --cov=app/v1

after_success:
    - coveralls
    - codecov
   