language: python
python:
  - '3.6' 

install:
    - pip install -r requirements.txt
    - pip install nose
    
before_script:
    - psql -c "CREATE DATABASE cop_bnk_hsing;" -U postgres
    - psql -c "CREATE DATABASE cop_bnk_hsing;" -U postgres
    - export FLASK_APP=run.py
    - export FLASK_DEBUG=1
    - export FLASK_ENV=development
    - export MAIL_SERVER='smtp.gmail.com'
    - export ADMIN_EMAIL='lilu@quickmail.rocks'
    - export ADMIN_FIRST_NAME='admin'
    - export ADMIN_LAST_NAME='default'
    - export ADMIN_PASSWORD='jacks278'
    - export ADMIN_OTHERNAME='kariuki'
    - export ADMIN_PHONENUMBER='07243834834'
    - export ADMIN_PSNUMBER='https://www.xmsicrosoft.com'

services:
    - postgresql

script:
    - nosetests --with-coverage --cover-package=copApp

after_success:
    - coveralls
   