language: python
python:
  - '3.5'
  - '3.6' 

install:
    - pip install -r requirements.txt
    - pip install nose
    - pip install coverage
    - pip install coveralls
before_script:
    - export FLASK_APP='run.py'
    - export FLASK_DEBUG=1
    - export FLASK_ENV=development
    - export FLASK_ENV=development
    - export DATABASE_URL="dbname='cop_bnk_hsing' user='postgres' host='localhost' password='admin'"
    - export TEST_DATABASE_URL="dbname='test_cop_bnk_hsing' user='postgres' host='localhost' password='admin'"
    - export MAIL_SERVER='smtp.gmail.com'

services:
    - postgresql

script:
    - nosetests --with-coverage --cover-package=app

after_success:
    - coveralls
    - codecov
   